server:
  port: 8084

spring:
  application:
  
    name: ApiGateway

  cloud:
    gateway:
      server:
        webmvc:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true
                max-age: 3600
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            - id: management-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**,/api/v1/grades,/api/v1/grades/**,/api/v1/lesson-types/**,/api/v1/study-weeks/**,/api/v1/timetable-templates/**,/api/v1/lessons/**,/api/v1/period-settings/**,/api/v1/periods/**,/api/v1/attendances/**,/api/v1/record-attendances/**,/api/v1/student/register,/api/v1/manager/student/register/**,/api/v1/manager/student/register,/api/v1/manager/students,/api/v1/online-lectures/**,/api/v1/learning-files/**,/api/v1/penalty-tags/**,/api/v1/penalties/**,/api/v1/cost-tags/**,/api/v1/costs/**,/api/v1/tham-sos/**,/api/v1/employee-ra-templates/**

            - id: exam-service
              uri: http://localhost:8080
              predicates:
                    - Path=/api/v1/exams,/api/v1/exams/**,/api/v1/questions,/api/v1/questions/**,/api/v1/question-groups,/api/v1/question-groups/**,/api/v1/student/exams/**,/api/v1/student/attempts,/api/v1/student/attempts/**,/api/v1/omr/**

            - id: management-service-api-docs
              uri: http://localhost:8081
              predicates:
                - Path=/docs/management-service/v3/api-docs
              filters:
                - RewritePath=/docs/management-service/(?<segment>.*), /$\{segment}

            - id: exam-service-api-docs
              uri: http://localhost:8080
              predicates:
                - Path=/docs/exam-service/v3/api-docs
              filters:
                - RewritePath=/docs/exam-service/(?<segment>.*), /$\{segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Management Service
        url: /docs/management-service/v3/api-docs
      - name: Exam Service
        url: /docs/exam-service/v3/api-docs
    urls-primary-name: Management Service

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
